### ISSUE TITLE
Add Prometheus/Grafana setup to FSAT

### ISSUE THREAD

**Issue by jkneubuh** [hyperledgendary/full-stack-asset-transfer-guide#12]
Add basic prometheus hooks to FSAT. 

Set up any peer / orderer config overrides in the CRD specs

Use a simple time series graph to show traffic / tx workloads distributed by the gateway client.

**Comment by jt-nti** [comment]
Closing now that this project has migrated to an official sample https://github.com/hyperledger/fabric-samples/tree/main/full-stack-asset-transfer-guide
